server.port=8086
server.address=0.0.0.0

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/auth_service_db
app.security.db-encryption-key=ThisIsASecretKey1234567890123456
spring.datasource.username=root
spring.datasource.password=adit9005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
app.jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
# 15 minutes
app.jwt.access-token-validity-ms=900000
# 30 days
# 365 days (1 year) for persistent mobile session
app.jwt.refresh-token-validity-ms=31536000000

# OTP Configuration
app.otp.validity-minutes=5
app.otp.max-attempts=5
app.otp.lock-duration-minutes=15
